### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Altamash347** [PresentKim/png-converter#1]
I need this but IDK how does it works

**Comment by PresentKim** [comment]
This is just a library that provides static methods.

Example...
````php
use kim\present\converter\png\PngConverter;
use pocketmine\network\mcpe\protocol\types\SkinImage;

/** @var SkinImage $skinImage */
$skinImage = PngConverter::toSkinImageFromFile("path/your/png/file");
````

----
This is virion project. You can use it with [poggit](https://poggit.pmmp.io/ci/PresentKim/png-converter).
- [Official Poggit Virion Documentation](https://poggit.github.io/support/virion.html) 

----

If you don't know virions usage, Just copy [this code](https://github.com/PresentKim/png-converter/blob/main/src/kim/present/converter/png/PngConverter.php) into your plugin. 

You are free to use the MIT licensed sources.
